### ISSUE TITLE
-ms- prefix should be lowercase in camelcase

### ISSUE THREAD

**Issue by jeanfredrik** [namuol/prefix-lite#2]
Hi! I love your package, but noticed one thing that you may want to take a look at.

When adding properties with vendor prefixes they are usually capitalized, but not `ms`. Example:

``` js
{
  justifyContent: 'flex-end', 
  MozJustifyContent: 'flex-end', 
  msJustifyContent: 'flex-end', /* lowercase vendor prefix */
  OJustifyContent: 'flex-end', 
  WebkitJustifyContent: 'flex-end', 
}
```

Read more here: http://www.andismith.com/blog/2012/02/modernizr-prefixed/

**Comment by jeanfredrik** [comment]
Oh, I just realized this package is no longer maintained. Sorry about that!

**Comment by namuol** [comment]
No worries! I just made the decision a week ago. Sorry to pull the rug out from under you like that...

But yeah, you should absolutely check out [inline-style-prefix-all](https://github.com/rofrischmann/inline-style-prefix-all) -- it's a much more thorough and similarly light solution.

**Comment by jeanfredrik** [comment]
No problem. I tried inline-style-prefix-all instead and it’s great :)
